### ISSUE TITLE
Is MetricPrefix mandatory?

### ISSUE THREAD

**Issue by brunoqc** [nathanielc/morgoth#15]
It seems my metrics needs to have the `m.` prefix. It could be nice if it was optional.
https://github.com/nvcook42/morgoth/blob/12a3183ec09e3a36e7259642d2c5e7f0ece723c6/metric/types/metric_id.go#L9

**Comment by nvcook42** [comment]
The intent here was to distinguish metrics from other types of series stored in influxdb.

In the current design there are three types of series stored in influxdb

1. Metrics - the raw metric data as morgoth received it.
2. Rotations - the metric data down sampled as per the schedules
3. Anomalies -  the anomalies are recorded as events in series

Each has its own prefix 'm.' 'rot.' and 'a.' respectively. Of note is that influxdb 0.9 is coming out in the next few weeks and will be able to add metadata to the series themselves. When this feature is implemented I plan to remove the metric prefixes and just store the type in the metadata. For now the type information has to be encoded into the metric name. 

For discussion, since this is brand new and I would appreciate your input.

The design of morgoth is that it makes the assumption that it owns the data. It receives the data and stores it into influxdb and morgoth controls the retention lengths of the different shard spaces in influxdb. What this means is that morgoth only stores the raw data long enough to be able to copy the down sampled data into each of the rotation series. Then the rotation series only keep the data for as long as the schedules dictate. 

My use case is that I use a system in front of morgoth like riemann and split the metric data stream. One stream goes to my generic metric aggregation system and the other stream goes into morgoth. Then I let morgoth detect anomalies and post back into the original metric data stream its findings.

Something like this:

Metrics --> Riemann --> (InfluxDB + Grafana)
Riemann --> Morgoth --> Riemann

This way I have one pane of glass Grafana to see all my metrics, and I just treat the anomalies as another metric. Note that Riemann stores data to a different InfluxDB database than Morgoth uses so they remain isolated.

**Comment by nathanielc** [comment]
This logic is now handled inside of the Kapacitor side of things which should provide more flexibility.
