### ISSUE TITLE
Support for influxDB 0.8.x

### ISSUE THREAD

**Issue by kumarnmanoj** [nathanielc/morgoth#26]
Whether the influxDB 0.8.x is supported?

As per the README morgoth integrates with graphite and mongodb also. Is there any reference/example for integration of the graphite or mongodb.

**Comment by nathanielc** [comment]
Morgoth only supports InfluxDB 0.9.x. I had an initial working backend on MongoDB but it quickly became very difficult to continue to support since I was essentially rewriting InfluxDB on top of MongoDB, which was bound to fail. As a result Morgoth now only support InfluxDB 0.9.x. It support graphite in that InfluxDB also uses the graphite protocol.

**Comment by Slach** [comment]
could you write some config examples for graphite support configuration ?

**Comment by deniszh** [comment]
If I understand correctly single way how you can do that is split your Graphite metric flow, send one part to InfluxDB and then working with InfluxDB. Fortunately Graphite parsing was fixed in InfluxDB 0.9 - http://influxdb.narkive.com/nXV0zqfL/graphite-protocol-broken-0-9-rc9

**Comment by nathanielc** [comment]
Closing since this is no longer possible/relevant
